# Generated by Django 3.1.1 on 2020-09-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('surname', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('job_type', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('installationManual', models.FileField(upload_to='Installation Manuals/')),
            ],
        ),
    ]
